# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})
    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: windows-latest, r: 'release'}
          - {os: macOS-latest, r: 'release'}
          - {os: ubuntu-20.04, r: 'release', rspm: "https://packagemanager.rstudio.com/cran/__linux__/focal/latest"}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: ${{ matrix.config.rspm }}
    
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - name: Install Dependencies (Windows)
        run: choco install glpk
        if: matrix.config.os == 'windows-latest'    
      - name: Install glpk (Windows)
        if: matrix.config.os == 'windows-latest'    
        shell: bash
        run: |
          echo $GITHUB_WORKSPACE >> $GITHUB_PATH
          curl -owinglpk-4.65.zip -L --insecure https://jaist.dl.sourceforge.net/project/winglpk/winglpk/GLPK-4.65/winglpk-4.65.zip
          7z x winglpk-4.65.zip
          cp glpk-4.65/w${{ matrix.windows-latest }}/glpk_4_65.lib glpk-4.65/w${{ matrix.windows-latest }}/glpk.lib
          echo ${GITHUB_WORKSPACE}\\glpk-4.65\\w${{ matrix.windows-latest }} >> $GITHUB_PATH
          echo GLPK_LIB_DIR=${GITHUB_WORKSPACE}\\glpk-4.65\\w${{ matrix.windows-latest }} >> $GITHUB_ENV
          echo GLPK_INCLUDE_DIR=${GITHUB_WORKSPACE}\\glpk-4.65\\src >> $GITHUB_ENV   
      - name: Install Dependencies (Linux)
        run: sudo apt-get install  libglpk-dev libglpk40 libc6 pandoc
        if: matrix.config.os == 'ubuntu-20.04'  
      - name: Install Dependencies (macOS)
        run: brew install pandoc
        if: matrix.config.os == 'macOS-latest'           
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck"))
          remotes::install_github("igraph/rigraph@master")
          remotes::install_cran("BiocManager")
          BiocManager::install("RBGL")
          remotes::install_deps(dependencies = TRUE)
          remotes::install_github("lcolladotor/biocthis")
          biocthis::use_bioc_github_action()
        shell: Rscript {0}             
      - name: Check
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}
